domain: inq28.paintsplastic.com
url: https://inq28.paintsplastic.com

title:    ==][==
author: PaintsPlastic

lang: en

plugins:
  - jekyll-seo-tag

color: "#000000" 

# disqus:
#   shortname: example-com
#
# rrss:
  # discord: hoola
  # facebook: hola
  # twitter: Hola
  # instagram: Hola
  # linkedin: Hola
  # pinterest: hola
  # whatsapp: 123
  # telegram: 123
  # email: email
